---
apiVersion: v1
kind: Secret
metadata:
  labels:
    k8s-app: kubernetes-dashboard
    app: kubernetes-dashboard
  name: kubernetes-dashboard-certs
  namespace: apps
type: Opaque

---
apiVersion: v1
kind: Secret
metadata:
  labels:
    k8s-app: kubernetes-dashboard
    app: kubernetes-dashboard
  name: kubernetes-dashboard-csrf
  namespace: apps
type: Opaque
data:
  csrf: ""

---
apiVersion: v1
kind: Secret
metadata:
  labels:
    k8s-app: kubernetes-dashboard
    app: kubernetes-dashboard
  name: kubernetes-dashboard-key-holder
  namespace: apps
type: Opaque
